services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: portofolio-react-app
    restart: always
    ports:
      - "${APP_PORT:-5001}:5173"
    volumes:
      - ./:/app
      - /app/node_modules

name: portofolio-react-app